name: Création de d'un artefact contenant le projet

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: 1) Récupère le code du repo
        uses: actions/checkout@v5

      - name: 2) Installation de nodejs
        uses: actions/setup-node@v4

      - name: 3) lint et build
        run: |
            npm audit fix
            npm run lint:check
            npm run build
            npm run build:firefox
         
      - name: 4) Upload l'artefact chrome
        uses: actions/upload-artifact@v4
        with: 
          name: artefact chrome
          path: .output/chrome-mv3

      - name: 5) Upload l'artefact firefox
        uses: actions/upload-artifact@v4
        with: 
          name: artefact firefox
          path: .output/firefox-mv2

